version: '3'
services:
    webhook-delegator:
        image: github-poc-webhook-delegator:step2
        build:
            context: ./webhook-delegator
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
